### ISSUE TITLE
no combat in claim

### ISSUE THREAD

**Issue by Deadeyeskunk** [SuperRonanCraft/Pueblos#5]
1.20.1 minecraft.  Enemies like zombies can walk into my claim in overworld and we can't hurt each other.  I attack but can't make contact and they bump into me also with no damage.  Zombies make poor roommates.

**Comment by SuperRonanCraft** [comment]
Finally fixed this after a user on Discord pointed out that projectiles don't work in a claim, this has been fixed as a result ;)
